## Numpy
* array (mutable) = 요소들의 테이블
* 요소가 모두 같은 데이터 타입
* 양의 정수로 구성된 튜플로 인덱싱
* numpy의 차원은 axis (axis 0 : ->)

In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

### array

In [7]:
a=np.array([2,3,4])
print(a)
print(type(a))
print(a.dtype)

a=[2,3,4]
print(type(a))

[2 3 4]
<class 'numpy.ndarray'>
int64
<class 'list'>


In [8]:
b=np.array([1.2, 4.3, 6.2])
b.dtype

dtype('float64')

In [9]:
c=np.array([[1,2,3],[4,5,6]])
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(c.data)

2
(2, 3)
6
int64
8


In [11]:
# ndarray

d=np.ndarray((2,2)) # shape을 input으로 받음
d # 안에는 랜덤한 값

array([[1.17048183e-316, 0.00000000e+000],
       [1.18565716e-316, 1.05940560e-316]])

In [12]:
e=np.array([[1,2],[3,4]], dtype=complex)
e

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [13]:
print(np.zeros((3,4))) # (3,4) shape을 가진 배열. 원소는 0으로 초기화

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
print(np.ones((2,3,4), dtype=np.int16)) # 3차원 array. 원소 1로 초기화

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [16]:
a=np.arange(10,30,5) # 시작값, 끝값, step
a

array([10, 15, 20, 25])

In [17]:
b=np.arange(0,2,0.3)
b

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [18]:
b=np.arange(0,2.1,0.3) # 끝 값인 2.1이 포함됨. step형이 실수일 경우 정확히 동작하지 x
b

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1])

In [19]:
c=np.linspace(0,2,9) # 시작값, 끝값, 개수
c

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [22]:
a=np.arange(10000)
print(a) # 배열이 너무 큰 경우 중간 부분 자동으로 생략해 print

[   0    1    2 ... 9997 9998 9999]


In [23]:
b=np.arange(10000).reshape(100,100) # 2차원 배열, 100*100으로 만들기
print(b)

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [ ]:
np.set_printoptions(threshold=sys.maxsize) # 배열 중간 생략하지 않고 모두 출력
print(b)

In [ ]:
np.set_printoptions(threshold=100) # 100개 넘어가면 생략해라
print(b)

### Array Indexing

In [32]:
x=np.arange(100,110)
print(x)

[100 101 102 103 104 105 106 107 108 109]


In [33]:
x[2]

102

In [34]:
x[-2]

108

In [35]:
x.resize(2,5) # 2*5 형태
print(x)

[[100 101 102 103 104]
 [105 106 107 108 109]]


In [36]:
print(x[1,3])

108


In [37]:
print(x[1][3])

108


In [38]:
print(x[1,-1])

109


In [39]:
print(x[0][-2])

103


In [40]:
print(x[0])

[100 101 102 103 104]


### list, array를 활용한 indexing

In [43]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [44]:
print(a[[0,1,2,0],[0,2,0,1]]) 
# [a[0,0], a[1,2], a[2,0], a[0,1]]

[1 6 7 2]


In [45]:
b=np.array([0,2,0,1])
print(a[b,b])
# [a[0,0], a[2,2], a[0,0], a[1,1]]

[1 9 1 5]


In [46]:
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


### [start : stop : step]

In [47]:
x[2:5] # index 2 ~ index 4

array([2, 3, 4])

In [49]:
x[:-7] # 처음 ~ index 2 (-7 = 3, stop point인 3은 포함x)

array([0, 1, 2])

In [50]:
x[1:7:2]

array([1, 3, 5])

In [52]:
y=np.arange(35).reshape(5,7)
print(y)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [54]:
y[1:5:2, ::3] # 1, 3행 중에서 0, 3, 6 열 출력

array([[ 7, 10, 13],
       [21, 24, 27]])

### Boolean indexing

In [55]:
a=np.array(range(6)).reshape(2,3) # range(6)=[0,1,2,3,4,5]
print(a)

[[0 1 2]
 [3 4 5]]


In [57]:
# 부등호 연산이 array 전체에서 가능하다!

bool_idx = a > 2 # 각각 요소를 돌면서 2보다 큰지 판별
print(bool_idx) # bool_idx 는 array 와 동일한 모양(2*3)

[[False False False]
 [ True  True  True]]


In [58]:
print(a[bool_idx]) # True 요소 만을 return

[3 4 5]


In [59]:
a=np.array(range(6)).reshape(2,3)
print(a[a>2]) # 동일한 결과

[3 4 5]


### Array Slicing

In [60]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [61]:
# shallow copy
# 슬라이싱에서 얕은 복사가 일어남. b는 a의 일부를 가리키는 것 뿐
b=a[:2] # 하나의 축(행)에 대한 인덱싱
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [62]:
c=a[:,1:3]
print(c)

[[ 2  3]
 [ 6  7]
 [10 11]]


In [65]:
b[0,0]=-1
print(b)

[[-1  2  3  4]
 [ 5  6  7  8]]


In [66]:
print(a)

[[-1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [67]:
# deep copy
b=np.copy(a[:2])
print(b)

[[-1  2  3  4]
 [ 5  6  7  8]]


In [68]:
b[0,0]=1
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [69]:
print(a)

[[-1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Shape Manipulation

In [74]:
a=np.floor(10*np.random.random((3,4))) # random 0~1
print(a)
print()
print(a.shape)
print()
print(a.ravel()) # 펼치기, a자체를 바꾸지는 않음. 반환만

[[3. 1. 7. 8.]
 [9. 6. 3. 8.]
 [7. 5. 3. 9.]]

(3, 4)

[3. 1. 7. 8. 9. 6. 3. 8. 7. 5. 3. 9.]


In [76]:
print(a.reshape(6,2)) # 반환만
print(a)

[[3. 1.]
 [7. 8.]
 [9. 6.]
 [3. 8.]
 [7. 5.]
 [3. 9.]]
[[3. 1. 7. 8.]
 [9. 6. 3. 8.]
 [7. 5. 3. 9.]]


In [78]:
a.resize(6,2) # a를 바꿈
print(a)

[[3. 1.]
 [7. 8.]
 [9. 6.]
 [3. 8.]
 [7. 5.]
 [3. 9.]]


In [79]:
print(a.T) # transpose

[[3. 7. 9. 3. 7. 3.]
 [1. 8. 6. 8. 5. 9.]]


In [82]:
a=np.floor(10*np.random.random((3,4)))
print(a)
print(a.reshape(6,-1)) #(6,2) : -1을 넣어주면 올바른 값으로 resize해줌

[[5. 5. 0. 1.]
 [4. 5. 7. 0.]
 [0. 1. 4. 5.]]
[[5. 5.]
 [0. 1.]
 [4. 5.]
 [7. 0.]
 [0. 1.]
 [4. 5.]]


In [87]:
a=np.floor(10*np.random.random((2,2)))
b=np.floor(10*np.random.random((2,2)))

print(a)
print()
print(b)
print()
print(np.vstack((a,b))) # 첫 번째 axis를 따라 쌓는다(행)

[[1. 2.]
 [8. 1.]]

[[0. 1.]
 [5. 8.]]

[[1. 2.]
 [8. 1.]
 [0. 1.]
 [5. 8.]]


In [89]:
print(np.hstack((a,b))) # 두 번째 axis를 따라 쌓는다(열)

[[1. 2. 0. 1.]
 [8. 1. 5. 8.]]


In [91]:
a=np.floor(10*np.random.random(12)).reshape(2,6)
print(a)
print()

np.hsplit(a,3) # 열 방향으로 나눈다.

[[4. 8. 4. 1. 6. 9.]
 [1. 7. 8. 2. 9. 6.]]



[array([[4., 8.],
        [1., 7.]]),
 array([[4., 1.],
        [8., 2.]]),
 array([[6., 9.],
        [9., 6.]])]

In [92]:
np.vsplit(a,2) # 행 방향으로 나눈다.

[array([[4., 8., 4., 1., 6., 9.]]), array([[1., 7., 8., 2., 9., 6.]])]

### 실습1

In [100]:
a=np.ones((5,5))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [101]:
b=np.zeros((5,5))
b[1:-1,1:-1]=1
print(b)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [106]:
x=np.ones((3,3))
print(x)
print()

x=np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 실습2

In [110]:
a=np.zeros((8,8),dtype=int)
a[::2, 1::2] = 1
a[1::2, ::2] = 1

print("Checkerboard pattern:")
print(a)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [109]:
a=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 실습3

In [113]:
a=np.array([180, 72, 172, 66, 162, 60, 167, 53, 176, 80, 155, 60, 177, 77, 130, 40])
a.resize(2,4,2)
print(a)
print()

print(a[1][1][0])

[[[180  72]
  [172  66]
  [162  60]
  [167  53]]

 [[176  80]
  [155  60]
  [177  77]
  [130  40]]]

155


### Basic Operations
* 산술연산은 기본으로 elementwise로 적용 : 각 자리끼리 연산

In [115]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

print(x+y)
print()

print(x-y)
print()

print(x*y)
print()

print(x/y)

[[ 6  8]
 [10 12]]

[[-4 -4]
 [-4 -4]]

[[ 5 12]
 [21 32]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [117]:
print(x<y)
print()

print(x>=y)
print()

print(x==y)
print()

print(x!=y)

[[ True  True]
 [ True  True]]

[[False False]
 [False False]]

[[False False]
 [False False]]

[[ True  True]
 [ True  True]]


In [118]:
a=np.array([20,30,40,50])
10*np.sin(a) # 0과 1 사이 작은 값이므로 그냥 10 곱해줌

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

#### 행렬 곱 : @, dot

In [119]:
a=np.array([[1,1],[0,1]])
b=np.array([[2,1],[3,4]])
a*b

array([[2, 1],
       [0, 4]])

In [120]:
a@b

array([[5, 5],
       [3, 4]])

In [121]:
a.dot(b)

array([[5, 5],
       [3, 4]])

In [124]:
a=np.random.random((2,3))
print(a)
print()

print(a.sum())
print(a.min())

[[0.15729386 0.39817888 0.58008238]
 [0.84460068 0.62919553 0.458885  ]]

3.068236333133259
0.15729386228569686


### Broadcasting
* elementwise 연산시 두 행렬이 같은 모양을 가져야함.
* 이때 모양이 같지 않을 경우 한 항의 값을 반대쪽 크기에 맞게 확장하는 것
* 후자 쪽이 자동으로 확장

In [123]:
x=np.array(range(1,13)).reshape(4,3)
print(x)
print()

v=np.array([1,0,1])
print(v)
print()

y=x+v # 내부적으로 broadcasting이 일어나서 자동으로 연산함
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 0 1]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### 주요 패키지
* numpy.linalg : 선형대수 관련 함수
* numpy.random : 난수 생성 관련 함수

### 실습4

In [126]:
def linear_system_solver(ndarr, v):
    y=np.linalg.inv(ndarr)@v
    return y

a=np.array([[1,1],[2,1]])
b=np.array([15,25])
c=linear_system_solver(a,b)
print(c)

[10.  5.]


### 실습5

In [127]:
data=np.random.random((4,6)).round(1)
length=np.array([4,1,6,3])

length=np.expand_dims(length,1)


[[0.  0.4 0.9 0.5 0.2 0.5]
 [0.8 0.1 0.5 0.7 0.7 0.3]
 [0.8 0.  0.9 0.5 0.9 0.3]
 [0.7 0.3 0.2 0.6 0.1 0.3]]


In [128]:
mask

[4 1 6 3]
